### ISSUE TITLE
Display comments from Wordpress blog on CSD website

### ISSUE THREAD

**Issue by IrenH** [clld/csd#3]
When someone leaves a comment on the blog they are not automatically displayed on the CSD website

**Comment by xrotwang** [comment]
Can you give an example? I.e. is there a published comment for any entry yet?

**Comment by IrenH** [comment]
Omaha 'egg' wittá

Check the blog, there are several test comments now

**Comment by xrotwang** [comment]
Can't see any:
https://comparativesiouandictionary.wordpress.com/2015/05/05/value-om-878-1-1/
You may have to explicitely publish comments from the wordpress admin page.

The one test comment I made does show up in the [feed](https://comparativesiouandictionary.wordpress.com/2015/05/05/value-om-878-1-1/) which the google feed API is supposed to fetch - but doesn't at the moment. This may be due to the site still being not publicly accessible, though.

**Comment by IrenH** [comment]
Ok, I have approved the comment now, it still doesn't show...
